WebSkillProfi/WebSkillProfi/Controllers/BlogsController.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.Design;
using WebSkillProfi.Data;
using WebSkillProfi.Interfaces;
using WebSkillProfi.Models;

namespace WebSkillProfi.Controllers
{
    public class BlogsController : Controller
    {
        private IBlogData _data;

        public BlogsController(IBlogData data)
        {
            _data = data;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _data.Blogs());
        }
    }
}

WebSkillProfi/WebSkillProfi/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.Design;
using WebSkillProfi.Data;
using WebSkillProfi.Interfaces;
using WebSkillProfi.Models;

namespace WebSkillProfi.Controllers
{
    public class ContactsController : Controller
    {
        private IContactData _data;

        public ContactsController(IContactData data)
        {
            _data = data;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _data.Contacts());
        }
    }
}

WebSkillProfi/WebSkillProfi/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.Design;
using WebSkillProfi.Data;
using WebSkillProfi.Interfaces;
using WebSkillProfi.Models;

namespace WebSkillProfi.Controllers
{
    public class ProjectsController : Controller
    {
        private IProjectData _data;

        public ProjectsController(IProjectData data)
        {
            _data = data;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _data.Projects());
        }
    }
}

WebSkillProfi/WebSkillProfi/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.Design;
using WebSkillProfi.Data;
using WebSkillProfi.Interfaces;
using WebSkillProfi.Models;

namespace WebSkillProfi.Controllers
{
    public class ServicesController : Controller
    {
        private IServiceData _data;

        public ServicesController(IServiceData data)
        {
            _data = data;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _data.Services());
        }
    }
}

WebSkillProfi/WebSkillProfi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html style="font-size: 16px;" lang="ru">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <title>Главная</title>
    <link rel="stylesheet" href="~/css/nicepage.css" media="screen">
    <link rel="stylesheet" href="~/css/style.css" media="screen">
    <link rel="stylesheet" href="~/css/media.css" media="screen">
    <meta name="generator" content="Nicepage 4.20.1, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="Главная">
    <meta property="og:type" content="website">
</head>
<body data-home-page="index.html" data-home-page-title="Главная" class="u-body u-xl-mode" data-lang="ru">
    <header class="u-header u-palette-1-base u-header" id="sec-c9af" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">
        <div class="u-clearfix u-sheet u-sheet-1">
            <a href="https://nicepage.com" class="u-image u-logo u-image-1" data-image-width="214" data-image-height="150">
                <img src="images/header.svg" class="u-logo-image u-logo-image-1" data-image-width="80">
            </a>
            <nav data-position="" class="u-menu u-menu-one-level u-offcanvas u-menu-1">
                <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px; font-weight: 700;">
                    <a class="u-button-style u-custom-active-border-color u-custom-border u-custom-border-color u-custom-borders u-custom-hover-border-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link" href="#" style="padding: 2px 0px; font-size: calc(1em + 4px);">
                        <svg class="u-svg-link" viewBox="0 0 24 24"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <defs>
                                <symbol id="menu-hamburger" viewBox="0 0 16 16" style="width: 16px; height: 16px;">
                                    <rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect>
                                    <rect y="13" width="16" height="2"></rect>
                                </symbol>
                            </defs>
                        </svg>
                    </a>
                </div>
                <div class="u-custom-menu u-nav-container">
                    <ul class="u-nav u-unstyled u-nav-1">
                        <li class="u-nav-item">
                            <a class="u-active-white u-button-style u-nav-link u-palette-1-base u-text-active-black u-text-hover-white" asp-controller="Home" asp-action="Index" style="padding: 10px 20px;">Главная</a>
                        </li>
                        <li class="u-nav-item">
                            <a class="u-active-white u-button-style u-nav-link u-palette-1-base u-text-active-black u-text-hover-white" asp-controller="Services" asp-action="Index" style="padding: 10px 20px;">Услуги</a>
                        </li>
                        <li class="u-nav-item">
                            <a class="u-active-white u-button-style u-nav-link u-palette-1-base u-text-active-black u-text-hover-white" asp-controller="Projects" asp-action="Index" style="padding: 10px 20px;">Проекты</a>
                        </li>
                        <li class="u-nav-item">
                            <a class="u-active-white u-button-style u-nav-link u-palette-1-base u-text-active-black u-text-hover-white" asp-controller="Blogs" asp-action="Index" style="padding: 10px 20px;">Блог</a>
                        </li>
                        <li class="u-nav-item">
                            <a class="u-active-white u-button-style u-nav-link u-palette-1-base u-text-active-black u-text-hover-white" asp-controller="Contacts" asp-action="Index" style="padding: 10px 20px;">Контакты</a>
                        </li>
                    </ul>
                </div>
                <div class="u-custom-menu u-nav-container-collapse">
                    <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
                        <div class="u-sidenav-overflow">
                            <div class="u-menu-close"></div>
                            <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2">
                                <li class="u-nav-item"><a class="u-button-style u-nav-link" asp-controller="Home" asp-action="Index">Главная</a></li>
                                <li class="u-nav-item"><a class="u-button-style u-nav-link" asp-controller="Services" asp-action="Index">Услуги</a></li>
                                <li class="u-nav-item"><a class="u-button-style u-nav-link" asp-controller="Projects" asp-action="Index">Проекты</a></li>
                                <li class="u-nav-item"><a class="u-button-style u-nav-link" asp-controller="Blogs" asp-action="Index">Блог</a></li>
                                <li class="u-nav-item"><a class="u-button-style u-nav-link" asp-controller="Contacts" asp-action="Index">Контакты</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
                </div>
            </nav>
            <img class="u-image u-image-default u-image-2" src="images/header.svg" alt="" data-image-width="1000" data-image-height="700">
            <p class="u-text u-text-default u-text-1 header-text">
                С НАМИ ЛЕГКО<br>
            </p>
        </div>
    </header>


    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-d43b">
        <div class="u-clearfix u-sheet u-sheet-1">
            <p class="u-small-text u-text u-text-variant u-text-1">Пример текста. Кликните, чтобы выбрать элемент "Текст".</p>
        </div>
    </footer>
    <section class="u-backlink u-clearfix u-grey-80">
        <a class="u-link" href="https://nicepage.com/website-templates" target="_blank">
            <span>Website Templates</span>
        </a>
        <p class="u-text">
            <span>created with</span>
        </p>
        <a class="u-link" href="" target="_blank">
            <span>Website Builder Software</span>
        </a>.
    </section>

    <script class="u-script" type="text/javascript" src="~/js/jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="~/js/nicepage.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="~/js/site.js" defer=""></script>
</body>
</html>
    